"""Builds doc/api/rpc.md, the JSON-RPC method reference, from the method tables in server.py.

    python scripts/gen_rpc_docs.py           # rewrite doc/api/rpc.md
    python scripts/gen_rpc_docs.py --check   # CI: fail if it is stale or a method has no docstring

Parameters are read with rpc_guard's own signature introspection, so the reference lists exactly
what validate accepts. Limits and parameter rules take their numbers from the code.
"""
import inspect
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import rpc_guard  # noqa: E402
import server  # noqa: E402
from engine import auth  # noqa: E402

OUT = ROOT / "doc" / "api" / "rpc.md"

TIERS = {  # server.TABLES kind -> (title, who may call, how the handler is called)
    "public": ("Public", "anyone, signed in or not", "gets the request context"),
    "account": ("Account", "signed in", "gets the request context"),
    "shared": ("Market data", "signed in; the same answer for every user", "gets the params only"),
    "user": ("User", "signed in; acts on the caller's own data", "gets the caller's `user_id` first"),
    "admin": ("Admin", "signed in, with the role feature listed in REQUIRES", "gets the request context"),
}

# Named in the method docstrings; the values come from the code.
LIMITS = [
    (server, "FORCE_SCREEN_EVERY", "seconds between forced screen refreshes, shared by all users"),
    (server, "DETAIL_EVAL_EVERY", "seconds between on-demand evaluations of one unscreened stock"),
    (server, "REPRICE_EVERY", "seconds between forced re-pricings, per user"),
    (auth, "SESSION_DAYS", "days a session lasts without use"),
    (auth, "SESSION_CAP_DAYS", "days a session lasts at most"),
    (auth, "FAIL_WINDOW", "seconds over which failed sign-ins are counted"),
    (auth, "FAILS_PER_PAIR", "failed sign-ins per email and IP in that window"),
    (auth, "FAILS_PER_IP", "failed sign-ins per IP in that window"),
    (auth, "SIGNUPS_PER_IP", "sign-ups per IP per hour"),
    (auth, "CODE_TTL", "seconds a sign-up code is valid"),
    (auth, "CODE_TRIES", "wrong guesses per sign-up code"),
    (auth, "VERIFY_PER_IP", "code checks per IP in 15 minutes"),
    (auth, "RESEND_GAP", "seconds between sign-up codes for one account"),
    (auth, "CODES_PER_IP", "sign-up codes sent per IP per hour"),
    (auth, "CODES_PER_DAY", "sign-up codes per account per 24 hours"),
    (auth, "CONFIRM_DAYS", "days to confirm the email before the sign-up is blocked"),
    (auth, "RESET_TTL", "seconds a password-reset link is valid"),
    (auth, "RESET_GAP", "seconds between reset emails for one account"),
    (auth, "RESET_PER_IP", "reset requests per IP per hour"),
]


def _cell(text: str) -> str:
    """A `|` inside a table cell, even in code, ends the cell unless escaped."""
    return text.replace("|", "\\|")


def _type(annotation) -> str:
    return "any" if annotation is inspect.Parameter.empty else inspect.formatannotation(annotation)


def _default(p) -> str:
    if p.default is p.empty:
        return "required"
    try:
        return f"`{json.dumps(p.default)}`"
    except TypeError:
        return f"`{p.default!r}`"


def _summary(doc: str) -> str:
    first = doc.split("\n\n")[0].replace("\n", " ")
    return _cell(first.split(". ")[0].rstrip(".") + ".")


def methods():
    """(name, tier kind, function) in table order."""
    return [(name, kind, fn) for table, kind in server.TABLES for name, fn in table.items()]


def method_section(name: str, fn) -> list[str]:
    sig = inspect.signature(fn)
    allowed, _ = rpc_guard._allowed(fn)
    server_only = [n for n in sig.parameters if n not in allowed]
    out = [f"### `{name}`", "", inspect.getdoc(fn), ""]
    if name in server.ANY_SYMBOL:
        out += ["`symbol` may be outside the Nifty 50: the method only acts on stocks the caller holds.", ""]
    if name in server.WHILE_MUST_CHANGE:
        out += ["Works while the account has a temporary password.", ""]
    if allowed:
        out += ["| Param | Type | Default |", "|---|---|---|"]
        out += [f"| `{n}` | `{_cell(_type(p.annotation))}` | {_default(p)} |" for n, p in allowed.items()]
        out.append("")
    else:
        out += ["No params.", ""]
    if server_only:
        out += [f"Set by the server, never by the client: {', '.join(f'`{n}`' for n in server_only)}.", ""]
    return out


def render() -> str:
    ms = methods()
    counts = {k: sum(1 for _, kind, _ in ms if kind == k) for k in TIERS}
    out = [
        "# JSON-RPC method reference",
        "",
        "<!-- Generated by scripts/gen_rpc_docs.py from server.py. Don't edit by hand: run `make rpc-docs`. -->",
        "",
        "Protocol, errors, CSRF, cookies and examples: [README.md](README.md).",
        "",
        f"{len(ms)} methods: " + ", ".join(f"{counts[k]} {TIERS[k][0].lower()}" for k in TIERS) + ".",
        "",
        "## Tiers",
        "",
        "| Tier | Who may call | Handler |",
        "|---|---|---|",
        *[f"| {t} | {who} | {how} |" for t, who, how in TIERS.values()],
        "",
        "## Index",
        "",
        "| Method | Tier | Summary |",
        "|---|---|---|",
        *[f"| [`{n}`](#{n}) | {TIERS[k][0].lower()} | {_summary(inspect.getdoc(fn))} |" for n, k, fn in ms],
        "",
        "## Parameter rules",
        "",
        "`rpc_guard.validate` checks every call before it reaches the handler:",
        "",
        "- `params` must be an object. Unknown names, missing required ones and wrong basic types are refused (error -32602).",
        "- Numbers must be finite (no NaN or Infinity).",
        f"- Strings are at most {rpc_guard.MAX_STR} characters.",
        "- `symbol` is an NSE ticker in the current Nifty 50, except where a method notes otherwise.",
        "- `expiry` is `YYYY-MM-DD`; `run_at` is `HH:MM`.",
        f"- `legs` is a list of 1 to {rpc_guard.MAX_LEGS} objects: `side` (`CE`/`PE`) and `strike` (> 0); order legs"
        f" add `action` (`BUY`/`SELL`), `lots` (1 to {rpc_guard.MAX_LOTS}) and an optional limit `price`.",
        f"- `lots` is 1 to {rpc_guard.MAX_LOTS}; `limit` is 1 to 500; `price` is above 0.",
        "",
        "## Limits",
        "",
        "Named in the method descriptions below.",
        "",
        "| Name | Value | Meaning |",
        "|---|---|---|",
        *[f"| `{n}` | {getattr(mod, n)} | {meaning} |" for mod, n, meaning in LIMITS],
        "",
    ]
    for kind, (title, who, _) in TIERS.items():
        out += [f"## {title} methods", "", f"Callable by: {who}.", ""]
        for n, k, fn in ms:
            if k == kind:
                out += method_section(n, fn)
    return "\n".join(out).rstrip("\n") + "\n"


def main() -> int:
    missing = [n for n, _, fn in methods() if not (inspect.getdoc(fn) or "").strip()]
    if missing:
        print(f"RPC methods without a docstring: {', '.join(missing)}", file=sys.stderr)
        return 1
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            print(f"{OUT.relative_to(ROOT)} is stale: run `make rpc-docs` and commit the result.", file=sys.stderr)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(methods())} methods)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
